language: go

go:
  - tip

before_install:
  - go get github.com/axw/gocov/gocov
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

install:
  - make get-deps

script:
  - make check
  - $HOME/gopath/bin/goveralls -repotoken ScR600zoS1GsDTmGSydufqvejP4bBpJj3

branches:
  only:
    - ng
