language: go

go:
  - 1.4

install:
  - make get-deps
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - make check
  - goveralls -coverprofile=coverage.out -service=travis-ci -repotoken ScR600zoS1GsDTmGSydufqvejP4bBpJj3

branches:
  only:
    - ng
